import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import ClientSidebar from "@/component/client/ClientSidebar";
import ClientNavbar from "@/component/client/ClientNavbar";
import ClientTokenHandler from "@/component/client/ClientTokenHandler";
import "@fortawesome/fontawesome-svg-core/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("access_token"); // Ganti has() dengan get()
  const isLoggedIn = !!accessToken; // Cek keberadaan token

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="w-full min-h-screen font-sans bg-gray-100 text-gray-900">
        {isLoggedIn ? (
          <>
            <ClientSidebar />
            <div className="ml-58 min-h-screen flex flex-col">
              <ClientNavbar />
              <ClientTokenHandler />
              <main className="flex-grow p-6 bg-blue-50">
                {children}
              </main>
            </div>
          </>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
